// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgCchnR6LmcGR9gFc3shyX11UAoDgzu0',
    appId: '1:633242387263:web:208addefeae0c22475c98a',
    messagingSenderId: '633242387263',
    projectId: 'share-flare-social-app',
    authDomain: 'share-flare-social-app.firebaseapp.com',
    storageBucket: 'share-flare-social-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6mCrOOvqrUIlVV9F7qXGR7mE64ULgMWA',
    appId: '1:633242387263:android:39cff3d1cdae0a0275c98a',
    messagingSenderId: '633242387263',
    projectId: 'share-flare-social-app',
    storageBucket: 'share-flare-social-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsylcswOmzMGSh8G4_-g06mMrP_AlCDu4',
    appId: '1:633242387263:ios:19bcc8fe4d31fa9e75c98a',
    messagingSenderId: '633242387263',
    projectId: 'share-flare-social-app',
    storageBucket: 'share-flare-social-app.appspot.com',
    iosBundleId: 'com.rezaulalam.shareFlare',
  );
}
